### ISSUE TITLE
Provide a multi-key docker cloud example

### ISSUE THREAD

**Issue by avandendorpe** [docker/dockercloud-authorizedkeys#5]
Docker-cloud supports YAML style mutiline definitions, e.g.

``` yaml
environment:
  authorized_keys: |-
    ssh-rsa ...
    ssh-rsa ...
```

Putting this in readme.md would be helpful!
